### ISSUE TITLE
server error for random song

### ISSUE THREAD

**Issue by ablissfulrose** [TechShivvy/spicetify-extensions#2]
![image](https://github.com/TechShivvy/spicetify-extensions/assets/148292249/962d0670-0ba1-47f8-982d-db8ea7307254)

**Comment by TechShivvy** [comment]
@ablissfulrose Server errors may occur 2 out of 10 times, and they sometimes resolve on their own. However, the current issue is due to recent changes at both Spicetify and Spotify's ends, necessitating adjustments to the core logic in the code. I'll address and resolve this issue asap.
